name: myethworld
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  simple_animations: ^3.2.0
  responsive_framework: ^0.1.4
  flutter_improved_scrolling: ^0.0.2
  flutterbook: ^0.1.3

  # State Management
  bloc: ^7.2.0-dev.3
  flutter_bloc: ^7.2.0
  get_it: ^7.2.0

  # Generators
  auto_route: ^2.3.2
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0
  provider: ^6.0.0
  google_fonts: ^2.1.0
  injectable: ^1.5.0
  flutter_web3: ^2.1.1
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^1.0.0

  # Generators
  auto_route_generator: ^2.3.2
  freezed: ^0.14.5
  json_serializable: ^5.0.1
  injectable_generator: ^1.5.2

dependency_overrides:
  provider: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tokens/

  # example:
  fonts:
    - family: SuisseIntl
      fonts:
        - asset: fonts/SuisseIntl-Regular.otf
        - asset: fonts/SuisseIntl-Medium.otf
          weight: 500
    - family: BrickDisplayPro
      fonts:
        - asset: fonts/BrickDisplayPro-Regular.ttf
